### ISSUE TITLE
A bit more explanation

### ISSUE THREAD

**Issue by scottjenson** [dermike/slide-beacon#1]
You're a busy guy! This looks great but I'm just not sure I understand exactly how this works. I think this is a request for your Readme to be a bit more clear. It would help to know how many things are running code and what the basic user flow is. I think it's:
1) Write slides in React.js
2) Each slide projects the current slides URL

But I wanted to be sure. In addition, I assume you're Mac is projecting the URL?

Scott

**Comment by dermike** [comment]
Thanks for checking it out @scottjenson! Will try to update the readme to clarify this. Right now it kind of assumes you know both Reveal.js (a great html presentational framework, not react) and node.

The node "server" part is what projects the url, and needs to run in the terminal while presenting the slides using reveal.js in your browser. (Or while pressing the [bookmarklet](https://github.com/dermike/eddystone-bookmarklet)). I hope the future WebBluetooth implementation can get rid of the nodejs requirement of these prototypes.

**Comment by dermike** [comment]
Hopefully better now
