### ISSUE TITLE
Feature Req. - Broadcast URL retention

### ISSUE THREAD

**Issue by JayHoltslander** [dermike/slide-beacon#14]
The Broadcast URL field should retain the last entered URL.

A broadcast URL history would be nice too. (eg: Use recent #2)

**Comment by dermike** [comment]
Great idea Jay! Will definitely look into URL history

**Comment by dermike** [comment]
@JayHoltslander I guess you mean this feature for https://github.com/dermike/slide-beacon-app ?

**Comment by JayHoltslander** [comment]
Whoops. Did I post this in the wrong spot? Yes I did mean that.

**Comment by dermike** [comment]
@JayHoltslander New 0.4.0 release up now with URL history: https://github.com/dermike/slide-beacon-app
Thanks again for the great suggestion! 😀
